-- Tasks to be performed:
-- 1. Display the number of states present in theLocationTable.

   SELECT
   COUNT(DISTINCT State) as [number_of_states]
   FROM
   [Location];


-- 2. How many products are of regular type?

    SELECT
	COUNT(Type) AS NUM
	FROM
	Product
	WHERE Type = 'REGULAR';


-- 3. Howmuch spending has been done on marketing of product ID1?
    
	SELECT
	SUM(Marketing) AS TOTAL_MARKET
	FROM
	fact
	WHERE ProductId = 1;


-- 4. What is the minimum sales of a product?

     SELECT TOP 1
	 ProductId,
	 SUM(Sales) AS TOTALS
	 FROM
	 fact
	 GROUP BY ProductId
	 ORDER BY TOTALS;


-- 5. Display the max Cost of Good Sold (COGS).
      
	 SELECT TOP 1
	 ProductId,
	 SUM(COGS) AS TOTALS
	 FROM
	 fact
	 GROUP BY ProductId
	 ORDER BY TOTALS DESC;


-- 6. Display the details of the product where product type iscoffee.

      SELECT
	  *
	  FROM
	  Product AS P
	  JOIN fact AS F ON P.ProductId = F.ProductId
	  WHERE P.Product_Type = 'COFFEE';


-- 7. Display the details where total expenses are greater than40.
      
	  SELECT
	  *
	  FROM
	  fact
	  where Total_Expenses > 40;


-- 8. What is the average sales in area code 719?
      
	  SELECT
	  AVG(Sales) AS AVERAGE
	  FROM
	  fact
	  WHERE Area_Code = 719;


-- 9. Find out the total profit generated by Colorado state.

      SELECT
	  State,
	  SUM(Profit)
	  FROM
	  fact AS F
	  JOIN Location AS L ON F.Area_Code = L.Area_Code
	  WHERE State = 'COLORADO'
	  GROUP BY State;



---10. Display the average inventory for each product ID.

     SELECT
	 ProductId,
	 AVG(Inventory)
	 FROM
	 fact
	 GROUP BY ProductId
	 ORDER BY ProductId;


--- 11. Display state in a sequential order in a LocationTable.

      SELECT
	  DISTINCT State
	  FROM
	  Location
	  ORDER BY State;


---12. Display the average budget of the Product where the average budget
        ---margin should be greater than 100.

       SELECT
	   ProductId,
	   AVG(Budget_Margin) AS AVERAGE
	   FROM
	   fact
	   GROUP BY ProductId
	   HAVING AVG(Budget_Margin) > 100;

	   
--- 13. What is the total sales done on date 2010-01-01?
       
	   SELECT
	   SUM(Sales) AS TOTAL
	   FROM
	   fact
	   WHERE [Date] = '2010-01-01';


---14. Display the average total expense of each product ID on an individual date.

      SELECT
	  ProductID,
	  [Date],
	  AVG(Total_Expenses) as average
	  FROM
	  Fact
	  GROUP BY ProductID, 
	  [Date]
	  order by ProductId;


---15. Display the table with the following attributes such as date, productID,
      ---product_type, product, sales, profit, state, area_code.

	  SELECT
	  [Date],
	  F.ProductId,
	  Product_Type,
	  Product,
	  Sales,
	  Profit,
	  State,
	  F.Area_Code
	  FROM
	  fact AS F
	  INNER JOIN Product AS P ON F.ProductId = P.ProductId
	  LEFT JOIN Location AS L ON F.Area_Code = L.Area_Code;

	  
---16.Display the rank without any gap to show the sales wiserank.

      SELECT
	  *,
	  DENSE_RANK() OVER(ORDER BY Sales) AS DRNK
	  FROM
	  fact;


--- 17.Find the state wise profit and sales.

      SELECT
	  State,
	  SUM(Profit) as total_profit,
	  SUM(Sales) as total_sales
	  FROM
	  Fact AS F
	  INNER JOIN Location AS L ON F.Area_Code = L.Area_Code
	  GROUP BY State;


 ---18. Find the state wise profit and sales along with the productname.
   
       SELECT
	  State,
	  Product,
	  SUM(Profit) as total_profit,
	  SUM(Sales) as total_sales
	  FROM
	  Fact AS F
	  INNER JOIN Location AS L ON F.Area_Code = L.Area_Code
	  left join Product as P on F.ProductID = P.ProductID 
	  GROUP BY State,Product;


---19.If there is an increase in sales of 5%, calculate the increasedsales.
 
      SELECT
	  *,
	  Sales * 1.05 AS increasedsales
	  FROM
	  fact;

---20.Find the maximum profit along with the product ID and producttype.

      SELECT
	  F.ProductId,
	  P.Product_Type,
	  SUM(Profit) AS [maximum profit]
	  FROM
	  fact AS F
	  INNER JOIN Product AS P ON F.ProductId = P.ProductId
	  GROUP BY F.ProductId,
	  P.Product_Type
	  ORDER BY  SUM(Profit) DESC;
GO

---21. Create a stored procedure to fetch the result according to theproduct type
       ---from ProductTable.

	   CREATE PROCEDURE SP_001(@X VARCHAR(30))
	   AS
	     BEGIN
	        SELECT
	        *
	        FROM
	        Product WHERE Product_Type = @X
		END;
GO

		EXEC SP_001 'Tea'
GO
 
---22. Write a query by creating a condition in which if the total expenses isless than
        ---60 then it is a profit or else loss.

       SELECT
	   *,
	     CASE WHEN Total_Expenses < 60 THEN 'PROFIT'
		      ELSE 'LOSS'
			  END profit_OR_loss
       FROM
	   fact;
GO

---23.Give the total weekly sales value with the date and product IDdetails. Use
      ---roll-up to pull the data in hierarchical order

	  SELECT
	  DATEADD(WEEK, DATEDIFF(WEEK, 0, [Date]), 0) AS Date,
	  ProductID,
	  SUM(Sales) as totals
	  FROM
	  fact
	  GROUP BY ROLLUP
	  (
	     DATEADD(WEEK, DATEDIFF(WEEK, 0, [Date]), 0),
	     ProductId
	  );
GO

 ---24.Apply union and intersection operator on the tables which consistof
      ---attribute area code.

	  SELECT Area_Code FROM fact
	  UNION
	  SELECT Area_Code FROM Location;
GO
-----------------------------------------------------------------------------
      SELECT Area_Code FROM fact
	  INTERSECT
	  SELECT Area_Code FROM Location;
GO


 ---25.Create a user-defined function for the product table to fetch aparticular
        ---product type based upon the user’s preference.

		CREATE FUNCTION FN_001(@user_preference VARCHAR(30))
		RETURNS TABLE
		AS
		RETURN(
		   SELECT * FROM Product AS P
		   WHERE P.Product_Type = @user_preference
			  );
GO

        SELECT * FROM dbo.FN_001('COFFEE'); 

        

---26. Change the product type from coffee to tea where product ID is 1and undo it.

          BEGIN TRANSACTION

           UPDATE Product
           SET Product_Type = REPLACE(Product_Type, 'COFFEE', 'TEA')
           WHERE ProductId = 1

          ROLLBACK TRANSACTION


          SELECT * FROM Product;


---27. Display the date, product ID and sales where total expensesare
       ---between 100 to 200.

	   SELECT
	   [Date],
	   ProductId,
	   Total_Expenses
	   FROM
	   fact
	   WHERE Total_Expenses BETWEEN 100 AND 200;


 ---28. Delete the records in the Product Table for regulartype.

       DELETE FROM Product WHERE Type = 'REGULAR';

	   
 ---29. Display the ASCII value of the fifth character from the columnProduct.

       SELECT 
        *,
        ASCII(SUBSTRING(Product, 5, 1)) AS FifthCharacterASCII
       FROM Product;

